title: Bölden
default_lang: sv
author:
  name: Bödlarna
  email: bodel@tf.fi
taxonomies:
  - category
  - tag
metadata:
  description: 'Välkommen till Böldens webbportal! Här finns all information rörande bölden, dess bokning och funktion.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
